# Generated by Django 5.1.4 on 2025-01-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_testimonial_alter_raffleentry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='payment_logos/')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
