# Generated by Django 5.1.4 on 2025-01-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_paymenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='color',
            field=models.CharField(default='warning', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
