# Generated by Django 5.1.4 on 2025-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_remove_paymenttype_additional_info_paymenttype_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
